### ISSUE TITLE
Error al levantar el proyecto

### ISSUE THREAD

**Issue by ajpy08** [joseandrescolmenares/create-documentation#1]
Al intentar levantar el proyecto en primera instancia me marca error con  
    experimental: {
      appDir: true,
    },

![image](https://github.com/joseandrescolmenares/create-documentation/assets/15370735/047b7363-4c1f-43d1-a8d3-e1b2bf74f37d)

estoy usando node 18.17.0 ya que es la minima requerida a pesar que el readme dice que 18 o superior. y estoy ejecutando el script npm run dev desde la rama main.

despues me sale el siguiente error:
![image](https://github.com/joseandrescolmenares/create-documentation/assets/15370735/30c154fa-842a-4fc7-b28e-013bcbd821dc)

sabras como podría solucionar el error?

**Comment by joseandrescolmenares** [comment]
Hey @ajpy08 ,

He investigado el problema y  Para solucionarlo, puedes intentar lo siguiente:

1. Abre tu archivo `next.config.js`.
2. Asegúrate de que la configuración experimental esté correctamente definida:
    ```javascript
    /** @type {import('next').NextConfig} */
    const nextConfig = {
        experimental: {
            appDir: true, //  eliminar esta linea de codigo ya que no es necesario 
        },
    };
      const withNextra =  nextra({
    theme: "nextra-theme-docs",
    themeConfig: "./theme.config.tsx",
  });
  
  export default  withNextra(nextConfig);
  
    
3. crea una carpeta llamada "pages" en la raiz del proyecto y dentro otra carpeta llamada "docs" 

![Screenshot 2024-06-14 at 5 31 23 PM](https://github.com/joseandrescolmenares/create-documentation/assets/70913085/62847db9-00ed-4d24-abe2-4d92ed8263d3)


3. Guarda los cambios y reinicia tu servidor de desarrollo.


Saludos.

**Comment by ajpy08** [comment]
Muchas gracias @joseandrescolmenares con los cambios mencionados logre levantar el proyecto muchas gracias.
